#!/bin/sh

#        _       _                _      
#       | |     | |              (_)     
#   __ _| |_ __ | |__   __ ___  ___ _ __ 
#  / _` | | '_ \| '_ \ / _` \ \/ / | '__| Shivaji Chalise (alphajr)
# | (_| | | |_) | | | | (_| |>  <| | |    http://www.github.com/shivajichalise
#  \__,_|_| .__/|_| |_|\__,_/_/\_\ |_|   
#         | |                   _/ |     
#         |_|                  |__/      
#
# Get a torrent's magnet link from cli and download using qbittorrent.

mkdir -p $HOME/.cache/magnet

baseUrl="https://1337x.to"
cacheDir="$HOME/.cache/magnet"

if [ -z $1 ]; then
  echo -n "Search Torrent: "
  read searchInput
else
  searchInput=$1
fi

searchInput="$(echo $searchInput | sed 's/ /%20/g')"

curl -s $baseUrl/sort-search/$searchInput/seeders/desc/1/ > $cacheDir/temp.html
# Get Titles
grep -o '<a href="/torrent/.*</a>' $cacheDir/temp.html | sed 's/<[^>]*>//g' | sed 's/^/  /' > $cacheDir/titles

count=$(wc -l $cacheDir/titles | awk '{print $1}')
if [ "$count" -lt 1 ]; then
  echo "No results found"
  printf "\033c"
  exit 0
fi

# Seeders and Leechers
grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' $cacheDir/temp.html | sed 's/<[^>]*>//g' | sed 'N;s/\n/ L:/' | sed 's/^/S:/' > $cacheDir/seedsleech

# Size
grep -o '<td class="coll-4 size.*</td>' $cacheDir/temp.html | sed 's/<span class="seeds">.*<\/span>//g' | sed -e 's/<[^>]*>//g' > $cacheDir/size

paste -d\  $cacheDir/seedsleech $cacheDir/size $cacheDir/titles > $cacheDir/final

# Links
grep -E '/torrent/' $cacheDir/temp.html | sed -E 's#.*(/torrent/.*)/">.*/#\1#' | sed 's/td>//g' > $cacheDir/links

linksFile="$cacheDir/final"
declare -a array
i=1
j=1
while read line
do		
	array[ $i ]=$j
	(( j++ ))
	array[ ($i + 1) ]=$line
        (( i=($i+2) ))
	
done < $linksFile

TERMINAL=$(tty)
HEIGHT=20
WIDTH=150
CHOICE_HEIGHT=16
BACKTITLE="https://github.com/shivajichalise"
TITLE="Download Torrent"
MENU="Choose:"

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${array[@]}" \
                2>&1 >$TERMINAL)

if [ -z "$CHOICE" ]; then
  echo "None Selected"
  printf "\033c"
  exit 0
else
  linkUrl=$(head -n $CHOICE $cacheDir/links | tail -n +$CHOICE)
  fullUrl="${baseUrl}${linkUrl}/"

  # get magnet link
  curl -s $fullUrl > $cacheDir/magnetLink
  magnet=$(grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" $cacheDir/magnetLink | head -n 1)
  qbittorrent "$magnet" &
fi

printf "\033c"
exit 0
